name: Build
on:
  pull_request:
    branches: [ '**' ]
  push:
    branches: [ '**' ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        scala: [ 2.12, 2.13 ]
        java:
          - adopt@1.8
        platform: [ jvm ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v14
        with:
          java-version: ${{ matrix.java }}

      - name: Set up Aerospike Database
        uses: reugn/github-action-aerospike@v1

      - name: Cache SBT
        uses: actions/cache@v4
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

      - name: Build and test
        run: sbt ++${{ matrix.scala }} test